# 개발환경
FROM node:14.15.3
WORKDIR /app/client
COPY ./package.json ./yarn.lock ./
RUN yarn install
COPY . .
CMD ["yarn", "serve"]
COPY . .

# 운영환경
#FROM node:14.15.3 as builder
#WORKDIR /app/client
#COPY ./package.json ./yarn.lock ./
#RUN yarn install
#COPY . .
#CMD ["yarn", "build"]

#FROM nginx
#COPY --from=builder /app/client/build /usr/share/nginx/html

#RUN yarn run build
## production stage
#FROM nginx:stable-alpine as production-stage
#COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
#COPY --from=build-stage /app/client/dist /usr/share/nginx/html
#EXPOSE 8081
#CMD ["nginx", "-g", "daemon off;"]

## build stage
#FROM node:lts-alpine as build-stage
#WORKDIR /app
#COPY package*.json ./
#RUN npm install --production
#COPY . .
#RUN npm run build
#
## production stage
#FROM nginx:stable-alpine as production-stage
#COPY --from=build-stage /app/dist /usr/share/nginx/html
#EXPOSE 80
#CMD ["nginx", "-g", "daemon off;"]
