version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/client/node_modules
      - ./client/:/app/client
#    ports:
#      - "8080:8080"
    stdin_open: true

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "8080:80"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - /app/server/node_modules
      - ./server/:/app/server
    env_file:
      - ./server/.env.dev
#    ports:
#      - "3000:3000"
    links:
      - mysql

  mysql:
    image: mysql:8
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'recommend'
      TZ: 'Asia/Seoul'
    ports:
      - '3311:3306'
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
