services:
  server:
    image: node:12-alpine
    working_dir: '/app'
    command: 'npm run start:dev'
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    links:
      - mysql
  mysql:
    image: mysql:8
    cap_add:
      - SYS_NICE
# container 가 제거되어도 데이터를 유지할 때 사용합니다.
#    volumes:
#      - ./ignored/database:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'sample'
      TZ: 'Asia/Seoul'
    ports:
      - '3311:3306'
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
